image: node:latest
stages:
- analyse
- build
- test
- deploy

before_script:
- npm i

run_tslint:
  stage: analyse
  script:
  - npm run analyse

run_tsc:
  stage: build
  script:
  - npm run build

run_tests:
  stage: test
  script:
  - npm test

publish:
  only:
  - tags
  stage: deploy
  script:
    - git fetch origin
    - npm version $(git describe --abbrev=0 --tags)
    - npm publish
